<?php
/**
 * ParentdetailObjTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * DCRC_CitizenDetailsAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ParentdetailObjTest Class Doc Comment
 *
 * @category    Class */
// * @description ParentdetailObj
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ParentdetailObjTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ParentdetailObj"
     */
    public function testParentdetailObj()
    {
    }

    /**
     * Test attribute "father_cid"
     */
    public function testPropertyFatherCid()
    {
    }

    /**
     * Test attribute "father_name"
     */
    public function testPropertyFatherName()
    {
    }

    /**
     * Test attribute "mother_cid"
     */
    public function testPropertyMotherCid()
    {
    }

    /**
     * Test attribute "mother_name"
     */
    public function testPropertyMotherName()
    {
    }
}
