<?php
/**
 * CitizendetailsObj
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * DCRC_CitizenDetailsAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * CitizendetailsObj Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CitizendetailsObj implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'citizendetailsObj';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'cid' => 'string',
        'first_name' => 'string',
        'middle_name' => 'string',
        'last_name' => 'string',
        'dob' => 'string',
        'gender' => 'string',
        'first_issued_date' => 'string',
        'household_no' => 'string',
        'mobile_number' => 'string',
        'occupation' => 'string',
        'country' => 'string',
        'father_name' => 'string',
        'mother_name' => 'string',
        'dzongkhag_id' => 'string',
        'dzongkhag_name' => 'string',
        'gewog_id' => 'string',
        'gewog_name' => 'string',
        'house_no' => 'string',
        'thram_no' => 'string',
        'village_serial_no' => 'string',
        'village_name' => 'string',
        'place_of_birth' => 'string',
        'first_dzo_name' => 'string',
        'middle_dzo_name' => 'string',
        'last_dzo_name' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'cid' => null,
        'first_name' => null,
        'middle_name' => null,
        'last_name' => null,
        'dob' => null,
        'gender' => null,
        'first_issued_date' => null,
        'household_no' => null,
        'mobile_number' => null,
        'occupation' => null,
        'country' => null,
        'father_name' => null,
        'mother_name' => null,
        'dzongkhag_id' => null,
        'dzongkhag_name' => null,
        'gewog_id' => null,
        'gewog_name' => null,
        'house_no' => null,
        'thram_no' => null,
        'village_serial_no' => null,
        'village_name' => null,
        'place_of_birth' => null,
        'first_dzo_name' => null,
        'middle_dzo_name' => null,
        'last_dzo_name' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'cid' => 'cid',
        'first_name' => 'firstName',
        'middle_name' => 'middleName',
        'last_name' => 'lastName',
        'dob' => 'dob',
        'gender' => 'gender',
        'first_issued_date' => 'firstIssuedDate',
        'household_no' => 'householdNo',
        'mobile_number' => 'mobileNumber',
        'occupation' => 'occupation',
        'country' => 'country',
        'father_name' => 'fatherName',
        'mother_name' => 'motherName',
        'dzongkhag_id' => 'dzongkhagId',
        'dzongkhag_name' => 'dzongkhagName',
        'gewog_id' => 'gewogId',
        'gewog_name' => 'gewogName',
        'house_no' => 'houseNo',
        'thram_no' => 'thramNo',
        'village_serial_no' => 'villageSerialNo',
        'village_name' => 'villageName',
        'place_of_birth' => 'placeOfBirth',
        'first_dzo_name' => 'firstDzoName',
        'middle_dzo_name' => 'middleDzoName',
        'last_dzo_name' => 'lastDzoName'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'cid' => 'setCid',
        'first_name' => 'setFirstName',
        'middle_name' => 'setMiddleName',
        'last_name' => 'setLastName',
        'dob' => 'setDob',
        'gender' => 'setGender',
        'first_issued_date' => 'setFirstIssuedDate',
        'household_no' => 'setHouseholdNo',
        'mobile_number' => 'setMobileNumber',
        'occupation' => 'setOccupation',
        'country' => 'setCountry',
        'father_name' => 'setFatherName',
        'mother_name' => 'setMotherName',
        'dzongkhag_id' => 'setDzongkhagId',
        'dzongkhag_name' => 'setDzongkhagName',
        'gewog_id' => 'setGewogId',
        'gewog_name' => 'setGewogName',
        'house_no' => 'setHouseNo',
        'thram_no' => 'setThramNo',
        'village_serial_no' => 'setVillageSerialNo',
        'village_name' => 'setVillageName',
        'place_of_birth' => 'setPlaceOfBirth',
        'first_dzo_name' => 'setFirstDzoName',
        'middle_dzo_name' => 'setMiddleDzoName',
        'last_dzo_name' => 'setLastDzoName'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'cid' => 'getCid',
        'first_name' => 'getFirstName',
        'middle_name' => 'getMiddleName',
        'last_name' => 'getLastName',
        'dob' => 'getDob',
        'gender' => 'getGender',
        'first_issued_date' => 'getFirstIssuedDate',
        'household_no' => 'getHouseholdNo',
        'mobile_number' => 'getMobileNumber',
        'occupation' => 'getOccupation',
        'country' => 'getCountry',
        'father_name' => 'getFatherName',
        'mother_name' => 'getMotherName',
        'dzongkhag_id' => 'getDzongkhagId',
        'dzongkhag_name' => 'getDzongkhagName',
        'gewog_id' => 'getGewogId',
        'gewog_name' => 'getGewogName',
        'house_no' => 'getHouseNo',
        'thram_no' => 'getThramNo',
        'village_serial_no' => 'getVillageSerialNo',
        'village_name' => 'getVillageName',
        'place_of_birth' => 'getPlaceOfBirth',
        'first_dzo_name' => 'getFirstDzoName',
        'middle_dzo_name' => 'getMiddleDzoName',
        'last_dzo_name' => 'getLastDzoName'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['cid'] = isset($data['cid']) ? $data['cid'] : null;
        $this->container['first_name'] = isset($data['first_name']) ? $data['first_name'] : null;
        $this->container['middle_name'] = isset($data['middle_name']) ? $data['middle_name'] : null;
        $this->container['last_name'] = isset($data['last_name']) ? $data['last_name'] : null;
        $this->container['dob'] = isset($data['dob']) ? $data['dob'] : null;
        $this->container['gender'] = isset($data['gender']) ? $data['gender'] : null;
        $this->container['first_issued_date'] = isset($data['first_issued_date']) ? $data['first_issued_date'] : null;
        $this->container['household_no'] = isset($data['household_no']) ? $data['household_no'] : null;
        $this->container['mobile_number'] = isset($data['mobile_number']) ? $data['mobile_number'] : null;
        $this->container['occupation'] = isset($data['occupation']) ? $data['occupation'] : null;
        $this->container['country'] = isset($data['country']) ? $data['country'] : null;
        $this->container['father_name'] = isset($data['father_name']) ? $data['father_name'] : null;
        $this->container['mother_name'] = isset($data['mother_name']) ? $data['mother_name'] : null;
        $this->container['dzongkhag_id'] = isset($data['dzongkhag_id']) ? $data['dzongkhag_id'] : null;
        $this->container['dzongkhag_name'] = isset($data['dzongkhag_name']) ? $data['dzongkhag_name'] : null;
        $this->container['gewog_id'] = isset($data['gewog_id']) ? $data['gewog_id'] : null;
        $this->container['gewog_name'] = isset($data['gewog_name']) ? $data['gewog_name'] : null;
        $this->container['house_no'] = isset($data['house_no']) ? $data['house_no'] : null;
        $this->container['thram_no'] = isset($data['thram_no']) ? $data['thram_no'] : null;
        $this->container['village_serial_no'] = isset($data['village_serial_no']) ? $data['village_serial_no'] : null;
        $this->container['village_name'] = isset($data['village_name']) ? $data['village_name'] : null;
        $this->container['place_of_birth'] = isset($data['place_of_birth']) ? $data['place_of_birth'] : null;
        $this->container['first_dzo_name'] = isset($data['first_dzo_name']) ? $data['first_dzo_name'] : null;
        $this->container['middle_dzo_name'] = isset($data['middle_dzo_name']) ? $data['middle_dzo_name'] : null;
        $this->container['last_dzo_name'] = isset($data['last_dzo_name']) ? $data['last_dzo_name'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets cid
     *
     * @return string
     */
    public function getCid()
    {
        return $this->container['cid'];
    }

    /**
     * Sets cid
     *
     * @param string $cid cid
     *
     * @return $this
     */
    public function setCid($cid)
    {
        $this->container['cid'] = $cid;

        return $this;
    }

    /**
     * Gets first_name
     *
     * @return string
     */
    public function getFirstName()
    {
        return $this->container['first_name'];
    }

    /**
     * Sets first_name
     *
     * @param string $first_name first_name
     *
     * @return $this
     */
    public function setFirstName($first_name)
    {
        $this->container['first_name'] = $first_name;

        return $this;
    }

    /**
     * Gets middle_name
     *
     * @return string
     */
    public function getMiddleName()
    {
        return $this->container['middle_name'];
    }

    /**
     * Sets middle_name
     *
     * @param string $middle_name middle_name
     *
     * @return $this
     */
    public function setMiddleName($middle_name)
    {
        $this->container['middle_name'] = $middle_name;

        return $this;
    }

    /**
     * Gets last_name
     *
     * @return string
     */
    public function getLastName()
    {
        return $this->container['last_name'];
    }

    /**
     * Sets last_name
     *
     * @param string $last_name last_name
     *
     * @return $this
     */
    public function setLastName($last_name)
    {
        $this->container['last_name'] = $last_name;

        return $this;
    }

    /**
     * Gets dob
     *
     * @return string
     */
    public function getDob()
    {
        return $this->container['dob'];
    }

    /**
     * Sets dob
     *
     * @param string $dob dob
     *
     * @return $this
     */
    public function setDob($dob)
    {
        $this->container['dob'] = $dob;

        return $this;
    }

    /**
     * Gets gender
     *
     * @return string
     */
    public function getGender()
    {
        return $this->container['gender'];
    }

    /**
     * Sets gender
     *
     * @param string $gender gender
     *
     * @return $this
     */
    public function setGender($gender)
    {
        $this->container['gender'] = $gender;

        return $this;
    }

    /**
     * Gets first_issued_date
     *
     * @return string
     */
    public function getFirstIssuedDate()
    {
        return $this->container['first_issued_date'];
    }

    /**
     * Sets first_issued_date
     *
     * @param string $first_issued_date first_issued_date
     *
     * @return $this
     */
    public function setFirstIssuedDate($first_issued_date)
    {
        $this->container['first_issued_date'] = $first_issued_date;

        return $this;
    }

    /**
     * Gets household_no
     *
     * @return string
     */
    public function getHouseholdNo()
    {
        return $this->container['household_no'];
    }

    /**
     * Sets household_no
     *
     * @param string $household_no household_no
     *
     * @return $this
     */
    public function setHouseholdNo($household_no)
    {
        $this->container['household_no'] = $household_no;

        return $this;
    }

    /**
     * Gets mobile_number
     *
     * @return string
     */
    public function getMobileNumber()
    {
        return $this->container['mobile_number'];
    }

    /**
     * Sets mobile_number
     *
     * @param string $mobile_number mobile_number
     *
     * @return $this
     */
    public function setMobileNumber($mobile_number)
    {
        $this->container['mobile_number'] = $mobile_number;

        return $this;
    }

    /**
     * Gets occupation
     *
     * @return string
     */
    public function getOccupation()
    {
        return $this->container['occupation'];
    }

    /**
     * Sets occupation
     *
     * @param string $occupation occupation
     *
     * @return $this
     */
    public function setOccupation($occupation)
    {
        $this->container['occupation'] = $occupation;

        return $this;
    }

    /**
     * Gets country
     *
     * @return string
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     *
     * @param string $country country
     *
     * @return $this
     */
    public function setCountry($country)
    {
        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets father_name
     *
     * @return string
     */
    public function getFatherName()
    {
        return $this->container['father_name'];
    }

    /**
     * Sets father_name
     *
     * @param string $father_name father_name
     *
     * @return $this
     */
    public function setFatherName($father_name)
    {
        $this->container['father_name'] = $father_name;

        return $this;
    }

    /**
     * Gets mother_name
     *
     * @return string
     */
    public function getMotherName()
    {
        return $this->container['mother_name'];
    }

    /**
     * Sets mother_name
     *
     * @param string $mother_name mother_name
     *
     * @return $this
     */
    public function setMotherName($mother_name)
    {
        $this->container['mother_name'] = $mother_name;

        return $this;
    }

    /**
     * Gets dzongkhag_id
     *
     * @return string
     */
    public function getDzongkhagId()
    {
        return $this->container['dzongkhag_id'];
    }

    /**
     * Sets dzongkhag_id
     *
     * @param string $dzongkhag_id dzongkhag_id
     *
     * @return $this
     */
    public function setDzongkhagId($dzongkhag_id)
    {
        $this->container['dzongkhag_id'] = $dzongkhag_id;

        return $this;
    }

    /**
     * Gets dzongkhag_name
     *
     * @return string
     */
    public function getDzongkhagName()
    {
        return $this->container['dzongkhag_name'];
    }

    /**
     * Sets dzongkhag_name
     *
     * @param string $dzongkhag_name dzongkhag_name
     *
     * @return $this
     */
    public function setDzongkhagName($dzongkhag_name)
    {
        $this->container['dzongkhag_name'] = $dzongkhag_name;

        return $this;
    }

    /**
     * Gets gewog_id
     *
     * @return string
     */
    public function getGewogId()
    {
        return $this->container['gewog_id'];
    }

    /**
     * Sets gewog_id
     *
     * @param string $gewog_id gewog_id
     *
     * @return $this
     */
    public function setGewogId($gewog_id)
    {
        $this->container['gewog_id'] = $gewog_id;

        return $this;
    }

    /**
     * Gets gewog_name
     *
     * @return string
     */
    public function getGewogName()
    {
        return $this->container['gewog_name'];
    }

    /**
     * Sets gewog_name
     *
     * @param string $gewog_name gewog_name
     *
     * @return $this
     */
    public function setGewogName($gewog_name)
    {
        $this->container['gewog_name'] = $gewog_name;

        return $this;
    }

    /**
     * Gets house_no
     *
     * @return string
     */
    public function getHouseNo()
    {
        return $this->container['house_no'];
    }

    /**
     * Sets house_no
     *
     * @param string $house_no house_no
     *
     * @return $this
     */
    public function setHouseNo($house_no)
    {
        $this->container['house_no'] = $house_no;

        return $this;
    }

    /**
     * Gets thram_no
     *
     * @return string
     */
    public function getThramNo()
    {
        return $this->container['thram_no'];
    }

    /**
     * Sets thram_no
     *
     * @param string $thram_no thram_no
     *
     * @return $this
     */
    public function setThramNo($thram_no)
    {
        $this->container['thram_no'] = $thram_no;

        return $this;
    }

    /**
     * Gets village_serial_no
     *
     * @return string
     */
    public function getVillageSerialNo()
    {
        return $this->container['village_serial_no'];
    }

    /**
     * Sets village_serial_no
     *
     * @param string $village_serial_no village_serial_no
     *
     * @return $this
     */
    public function setVillageSerialNo($village_serial_no)
    {
        $this->container['village_serial_no'] = $village_serial_no;

        return $this;
    }

    /**
     * Gets village_name
     *
     * @return string
     */
    public function getVillageName()
    {
        return $this->container['village_name'];
    }

    /**
     * Sets village_name
     *
     * @param string $village_name village_name
     *
     * @return $this
     */
    public function setVillageName($village_name)
    {
        $this->container['village_name'] = $village_name;

        return $this;
    }

    /**
     * Gets place_of_birth
     *
     * @return string
     */
    public function getPlaceOfBirth()
    {
        return $this->container['place_of_birth'];
    }

    /**
     * Sets place_of_birth
     *
     * @param string $place_of_birth place_of_birth
     *
     * @return $this
     */
    public function setPlaceOfBirth($place_of_birth)
    {
        $this->container['place_of_birth'] = $place_of_birth;

        return $this;
    }

    /**
     * Gets first_dzo_name
     *
     * @return string
     */
    public function getFirstDzoName()
    {
        return $this->container['first_dzo_name'];
    }

    /**
     * Sets first_dzo_name
     *
     * @param string $first_dzo_name first_dzo_name
     *
     * @return $this
     */
    public function setFirstDzoName($first_dzo_name)
    {
        $this->container['first_dzo_name'] = $first_dzo_name;

        return $this;
    }

    /**
     * Gets middle_dzo_name
     *
     * @return string
     */
    public function getMiddleDzoName()
    {
        return $this->container['middle_dzo_name'];
    }

    /**
     * Sets middle_dzo_name
     *
     * @param string $middle_dzo_name middle_dzo_name
     *
     * @return $this
     */
    public function setMiddleDzoName($middle_dzo_name)
    {
        $this->container['middle_dzo_name'] = $middle_dzo_name;

        return $this;
    }

    /**
     * Gets last_dzo_name
     *
     * @return string
     */
    public function getLastDzoName()
    {
        return $this->container['last_dzo_name'];
    }

    /**
     * Sets last_dzo_name
     *
     * @param string $last_dzo_name last_dzo_name
     *
     * @return $this
     */
    public function setLastDzoName($last_dzo_name)
    {
        $this->container['last_dzo_name'] = $last_dzo_name;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


