<?php
/**
 * ParentdetailObj
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * DCRC_CitizenDetailsAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * ParentdetailObj Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ParentdetailObj implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'parentdetailObj';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'father_cid' => 'string',
        'father_name' => 'string',
        'mother_cid' => 'string',
        'mother_name' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'father_cid' => null,
        'father_name' => null,
        'mother_cid' => null,
        'mother_name' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'father_cid' => 'fatherCID',
        'father_name' => 'fatherName',
        'mother_cid' => 'motherCID',
        'mother_name' => 'motherName'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'father_cid' => 'setFatherCid',
        'father_name' => 'setFatherName',
        'mother_cid' => 'setMotherCid',
        'mother_name' => 'setMotherName'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'father_cid' => 'getFatherCid',
        'father_name' => 'getFatherName',
        'mother_cid' => 'getMotherCid',
        'mother_name' => 'getMotherName'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['father_cid'] = isset($data['father_cid']) ? $data['father_cid'] : null;
        $this->container['father_name'] = isset($data['father_name']) ? $data['father_name'] : null;
        $this->container['mother_cid'] = isset($data['mother_cid']) ? $data['mother_cid'] : null;
        $this->container['mother_name'] = isset($data['mother_name']) ? $data['mother_name'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets father_cid
     *
     * @return string
     */
    public function getFatherCid()
    {
        return $this->container['father_cid'];
    }

    /**
     * Sets father_cid
     *
     * @param string $father_cid father_cid
     *
     * @return $this
     */
    public function setFatherCid($father_cid)
    {
        $this->container['father_cid'] = $father_cid;

        return $this;
    }

    /**
     * Gets father_name
     *
     * @return string
     */
    public function getFatherName()
    {
        return $this->container['father_name'];
    }

    /**
     * Sets father_name
     *
     * @param string $father_name father_name
     *
     * @return $this
     */
    public function setFatherName($father_name)
    {
        $this->container['father_name'] = $father_name;

        return $this;
    }

    /**
     * Gets mother_cid
     *
     * @return string
     */
    public function getMotherCid()
    {
        return $this->container['mother_cid'];
    }

    /**
     * Sets mother_cid
     *
     * @param string $mother_cid mother_cid
     *
     * @return $this
     */
    public function setMotherCid($mother_cid)
    {
        $this->container['mother_cid'] = $mother_cid;

        return $this;
    }

    /**
     * Gets mother_name
     *
     * @return string
     */
    public function getMotherName()
    {
        return $this->container['mother_name'];
    }

    /**
     * Sets mother_name
     *
     * @param string $mother_name mother_name
     *
     * @return $this
     */
    public function setMotherName($mother_name)
    {
        $this->container['mother_name'] = $mother_name;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


