<?php
/**
 * HouseholdingdetailsObjTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * DCRC_CitizenDetailsAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * HouseholdingdetailsObjTest Class Doc Comment
 *
 * @category    Class */
// * @description HouseholdingdetailsObj
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class HouseholdingdetailsObjTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "HouseholdingdetailsObj"
     */
    public function testHouseholdingdetailsObj()
    {
    }

    /**
     * Test attribute "cid"
     */
    public function testPropertyCid()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "dob"
     */
    public function testPropertyDob()
    {
    }

    /**
     * Test attribute "father_name"
     */
    public function testPropertyFatherName()
    {
    }

    /**
     * Test attribute "first_issued_date"
     */
    public function testPropertyFirstIssuedDate()
    {
    }

    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {
    }

    /**
     * Test attribute "gender"
     */
    public function testPropertyGender()
    {
    }

    /**
     * Test attribute "household_no"
     */
    public function testPropertyHouseholdNo()
    {
    }

    /**
     * Test attribute "last_name"
     */
    public function testPropertyLastName()
    {
    }

    /**
     * Test attribute "middle_name"
     */
    public function testPropertyMiddleName()
    {
    }

    /**
     * Test attribute "mobile_number"
     */
    public function testPropertyMobileNumber()
    {
    }

    /**
     * Test attribute "mother_name"
     */
    public function testPropertyMotherName()
    {
    }

    /**
     * Test attribute "occupation"
     */
    public function testPropertyOccupation()
    {
    }

    /**
     * Test attribute "dzongkhag_id"
     */
    public function testPropertyDzongkhagId()
    {
    }

    /**
     * Test attribute "dzongkhag_name"
     */
    public function testPropertyDzongkhagName()
    {
    }

    /**
     * Test attribute "gewog_id"
     */
    public function testPropertyGewogId()
    {
    }

    /**
     * Test attribute "gewog_name"
     */
    public function testPropertyGewogName()
    {
    }

    /**
     * Test attribute "house_no"
     */
    public function testPropertyHouseNo()
    {
    }

    /**
     * Test attribute "thram_no"
     */
    public function testPropertyThramNo()
    {
    }

    /**
     * Test attribute "village_serial_no"
     */
    public function testPropertyVillageSerialNo()
    {
    }

    /**
     * Test attribute "village_name"
     */
    public function testPropertyVillageName()
    {
    }

    /**
     * Test attribute "place_of_birth"
     */
    public function testPropertyPlaceOfBirth()
    {
    }
}
